apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rechnungspost.fullname" . }}
  namespace: rechnungspost
  labels:
    {{- include "rechnungspost.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rechnungspost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rechnungspost.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "rechnungspost.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "rechnungspost.fullname" . }}-config
            - secretRef:
                name: {{ include "rechnungspost.fullname" . }}-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
