{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rechnungspost.fullname" . }}-migrate-{{ .Release.Revision }}
  namespace: rechnungspost
  labels:
    {{- include "rechnungspost.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}"
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - configMapRef:
                name: {{ include "rechnungspost.fullname" . }}-config
            - secretRef:
                name: {{ include "rechnungspost.fullname" . }}-secrets
{{- end }}
