apiVersion: v1
kind: Service
metadata:
  name: {{ include "rechnungspost.fullname" . }}
  namespace: rechnungspost
  labels:
    {{- include "rechnungspost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "rechnungspost.selectorLabels" . | nindent 4 }}
